---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/karthikbattula/pluralsight-spring-cloudconfig-sample # default
          #username: 
          #password: 
          search-paths:
            - 'Station*'
          repos:
             perf:
                pattern: '*/perf'
                uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-perf # alt
                search-paths:
                 - 'station*'
security:
  basic:
    enabled: true
  user:
    name: pluralsight
    password: pluralsight